### ISSUE TITLE
Please move to the new API

### ISSUE THREAD

**Issue by DunkelBlauer** [danieleff/nextrocket.space#10]
Hey, first of all i want to thank you for this great website. i've been using it for years and celebrate it every time again. thank you!

Since a few days I notice the following message in the list of starts: **Please move to the new API @ thespacedevs.com**
How can I fix the message - or is this a topic for the website api itself?

BR
Jan

**Comment by TheBlacktom** [comment]
Hey, the message is addressed to the API users/developers. Funnily enough
Launch Library people included the message into the launch data itself so
everyone sees it until we manually filter it out or migrate to the new API.
You don't have to do anything with it, sorry for the confusion. Also thanks
for using the site.

Tamás
