### ISSUE TITLE
Any chance for a json api for upcoming launches by company?

### ISSUE THREAD

**Issue by FeepingCreature** [danieleff/nextrocket.space#6]
I have an IRC bot that lists the next SpaceX launch. It used to extract the info from the /r/spacex subreddit sidebar, but that's been really unreliable as of late. Load estimate is maybe one query an hour at most, realistically once a day.

edit: Also you probably shouldn't allow just anyone to update the database.

**Comment by FeepingCreature** [comment]
Nmind, I went with launchlibrary.net.

**Comment by TheBlacktom** [comment]
What do you mean by allowing just anyone to update the database?
