### ISSUE TITLE
Date / Time fields overrun adjacent info with Firefox

### ISSUE THREAD

**Issue by andrewbird** [danieleff/nextrocket.space#9]
As you can see from the screenshots below, the date/time fields overrun the adjacent columns when they include the time not just the date. It's not that there isn't enough free space on the width, because other columns in the row have plenty of room.

I'm using Firefox on Linux, whereas on Chromium the display is fine.

![nextlaunch2](https://user-images.githubusercontent.com/220835/83620024-9f979900-a584-11ea-820a-e8629f0057ff.png)

![nextlaunch](https://user-images.githubusercontent.com/220835/83619777-42034c80-a584-11ea-910e-f9b2be601c2f.png)

**Comment by danieleff** [comment]
I uploaded a fix for this, could you check again?

**Comment by andrewbird** [comment]
Thanks very much for the prompt response and fix, that looks great now!
![nextlaunch3](https://user-images.githubusercontent.com/220835/83647935-61629f80-a5ad-11ea-92c6-232158df4094.png)
